---
application:
  name: "hill-chart-api"
  project: "hill-chart-api"
  organization: "QoveryCommunity"
routers:
- name: "main-hill-chart-api"
  routes:
  - application_name: "hill-chart-api"
    paths:
    - "/*"
